import { initI18nextConfig } from "@/common/i18n/i18n.server";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import I18nProvider from "./_components/I18nProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export type Language = "en" | "ko";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const getBrowserLanguage = () => {
  const lang = headers().get("x-url")?.split("/")?.[3];

  return (lang ?? "en") as Language;
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const lang = getBrowserLanguage();
  initI18nextConfig(lang);

  return (
    <html lang={lang}>
      <body className={inter.className}>
        <I18nProvider lang={lang}>{children}</I18nProvider>
      </body>
    </html>
  );
}
