#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# 1. 브랜치명
#
# prefix/ticket-name
#
# 2. 커밋 메시지에 브랜치명 규칙에 기반한 이슈번호 자동 생성
#
# ... commit-msg git-hooks 참고 ...
#
# 접미사 [#(이슈번호)] 자동 생성

COMMIT_MSG_FILE=$1

addBranchNumber() {
  BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
  ISSUE_NAME=`echo $BRANCH_NAME | cut -d '/' -f2`
  DESCRIPTION=$(git config branch."$BRANCH_NAME".description)

  echo "[$ISSUE_NAME] $(cat $COMMIT_MSG_FILE)" > $COMMIT_MSG_FILE

  if [ -n "$DESCRIPTION" ]
  then
    echo "" >> $COMMIT_MSG_FILE
    echo $DESCRIPTION >> $COMMIT_MSG_FILE
  fi
}

MERGE=$(cat $COMMIT_MSG_FILE|grep -i 'merge'|wc -l)

if [ $MERGE -eq 0 ] ; then
  addBranchNumber
fi
